### PR TITLE
Fix visionOS build in Xcode 15.1 beta 1

### LINKED ISSUE #130: Usage of TARGET_OS_IPHONE breaks visionOS simulator (Xcode 15.1 beta 1)
https://github.com/google/GoogleUtilities/blob/1a4c036647e3b056291610d7d8dec93e104d046d/GoogleUtilities/Environment/GULAppEnvironmentUtil.m#L170

The line above should use `TARGET_OS_IOS` instead `TARGET_OS_IPHONE`. Using `TARGET_OS_IPHONE` makes this section valid in the Vision simulator. The definition of target defs are as follows in TargetConditionals.h on Xcode 15.1 beta 1 for the vision sim:

```
 #if (__is_target_arch(x86_64) || __is_target_arch(arm64) || __is_target_arch(arm64e)) && __is_target_vendor(apple) && __is_target_os(xros) && __is_target_environment(simulator)
        #define TARGET_OS_MAC               1
        #define TARGET_OS_OSX               0
        #define TARGET_OS_IPHONE            1

        #define TARGET_OS_IOS               0

        #define TARGET_OS_WATCH             0
        
        #define TARGET_OS_TV                0
        #define TARGET_OS_SIMULATOR         1
        #define TARGET_OS_EMBEDDED          0
        #define TARGET_OS_RTKIT             0
        #define TARGET_OS_MACCATALYST       0
        #define TARGET_OS_MACCATALYST            0

        #define TARGET_OS_VISION            1
        
        
        #ifndef TARGET_OS_UIKITFORMAC
         #define TARGET_OS_UIKITFORMAC      0
        #endif
        #define TARGET_OS_DRIVERKIT         0
        #define DYNAMIC_TARGETS_ENABLED     1
    #endif
```

### PR DESCRIPTION
**Pull request by andrewheard**
In Xcode 15.1 `TARGET_OS_IOS` is now `0` instead of `1`. This PR fixes the build on visionOS (and resolves #130) but does not address all issues in tests.

In follow-ups we should audit uses of `TARGET_OS_IOS` throughout the codebase.

### CODE REVIEW

File: GoogleUtilities/Environment/GULAppEnvironmentUtil.m [hunk 1]
```diff
@@ -191,7 +191,7 @@ + (NSString *)deviceSimulatorModel {
 }
 
 + (NSString *)systemVersion {
-#if TARGET_OS_IOS
+#if TARGET_OS_IOS || TARGET_OS_VISION
   return [UIDevice currentDevice].systemVersion;
```
Comment (paulb777) [inline GoogleUtilities/Environment/GULAppEnvironmentUtil.m:195]: Did you test this on VisionOS?

File: GoogleUtilities/Environment/GULAppEnvironmentUtil.m [hunk 2]
```diff
@@ -21,7 +21,7 @@
 
 #import "third_party/IsAppEncrypted/Public/IsAppEncrypted.h"
 
-#if TARGET_OS_IOS
+#if TARGET_OS_IOS || TARGET_OS_VISION
```
Comment (paulb777) [inline GoogleUtilities/Environment/GULAppEnvironmentUtil.m:24]: This doesn't seem right without changing the code involving UIDevice below ...

File: GoogleUtilities/Environment/GULAppEnvironmentUtil.m (hunk 1 above)
Comment (paulb777) [reply GoogleUtilities/Environment/GULAppEnvironmentUtil.m:195]: What is the systemVersion?

Comment (andrewheard) [reply GoogleUtilities/Environment/GULAppEnvironmentUtil.m:195]: Yep, it returns `"1.0"` on the visionOS simulator at least. I'm not sure why we handle `TARGET_OS_TV` separately below since macOS and watchOS are the only platforms where [UIDevice](https://developer.apple.com/documentation/uikit/uidevice) isn't available -- need to download a tvOS simulator to check the behaviour there.

Comment (paulb777) [reply GoogleUtilities/Environment/GULAppEnvironmentUtil.m:195]: We might have wanted to avoid the UIKit dependency but needed it for iOS because of backwards compatibility

Comment (andrewheard) [reply GoogleUtilities/Environment/GULAppEnvironmentUtil.m:197]: I updated it to use the `#elif` below since it works on visionOS as well and doesn't have the UIKit dependency.

**Review by paulb777 — APPROVED** [review]
Thanks!
