### PR TITLE
[Environment] Rename parameter to avoid conflict with keyword

### LINKED ISSUE #152: Debug error
I have this repository as package dependency in my project, after switching in build settings " C++ and Objective-C Interpretability" to C++/Objective-C++ I have an error during debugging 
error: couldn't IRGen expression: Clang importer error
error: /Users/user/Library/Developer/Xcode/DerivedData/ProjectName-eqlgtjjbjxfjgahdtsezsljspzsa/SourcePackages/checkouts/GoogleUtilities/GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h:28:47: error: expected identifier; 'class' is a keyword in Objective-C++
+ (nullable id)unarchivedObjectOfClass:(Class)class
so what can I do with that?

### LINKED ISSUE #153: Error in iOS app about NSKeyedUnarchiver
iOS 16.4.1
XCode 15.1

When our app startup, I see some error.

> *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x1e169ef58) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSSet' (0x1e16974d8) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.

NSKeyedUnarchiver is used in GULSecureCoding.m

### PR DESCRIPTION
**Pull request by ncooke3**
Fix #152

### CODE REVIEW

File: GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h [hunk 1]
```diff
@@ -25,7 +25,7 @@ NS_ASSUME_NONNULL_BEGIN
                                 fromData:(NSData *)data
                                    error:(NSError **)outError;
 
-+ (nullable id)unarchivedObjectOfClass:(Class)class
++ (nullable id)unarchivedObjectOfClass:(Class)aClass
```
Comment (ncooke3) [inline GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h:28]: Would this change need to wait for a major version bump?  At first, I thought yes, but am now less sure since the method signature/type remains the same.

Comment (andrewheard) [reply GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h:28]: My hunch is that this would be fine in a patch release since even in less common scenarios, like calling indirectly with ObjC runtime methods, the param name isn't involved (at least not in the ones I've seen). Might be good to wait for Paul to give a second opinion though.

**Review by andrewheard — APPROVED** [review]
LGTM but please wait for a second approval.

File: GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h (hunk 1 above)
Comment (paulb777) [reply GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h:28]: Agreed, it shouldn't be breaking - and as far as I can tell, this API isn't being used and may not have been for awhile.

Comment (ncooke3) [reply GoogleUtilities/Environment/Public/GoogleUtilities/GULSecureCoding.h:28]: Thank you both!
